version: "3.3"


services:
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  web:
    build: 
      context: .
      dockerfile: ./Dockerfile
    image: django_celery_example_web
    command: /start
    volumes:
      - .:/usr/src/Notification_service
    ports:
      - 8000:8000 
    env_file:
      - ./config/.env
    depends_on: 
      - redis
      - db
  celery_worker:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: django_celery_example_celery_worker
    command: /start-celeryworker
    volumes:
      - .:/app
    env_file:
      - ./config/.env
    depends_on:
      - redis
      - db
  celery_beat:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: django_celery_example_celery_beat
    command: /start-celerybeat
    volumes:
      - .:/app
    env_file:
      - ./config/.env
    depends_on:
      - redis
      - db
volumes:
  postgres_data: