# Generated by Django 4.2.1 on 2023-05-11 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=10)),
                ('timezone', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенти',
            },
        ),
        migrations.CreateModel(
            name='CodeMobileOperatorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=3)),
            ],
            options={
                'verbose_name': 'Код мобильного оператора',
                'verbose_name_plural': 'Код мобильного оператора',
            },
        ),
        migrations.CreateModel(
            name='MailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('text', models.TextField()),
                ('end_date', models.DateTimeField()),
                ('code_mobile_operators', models.ManyToManyField(to='main.codemobileoperatormodel')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='MessageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('Retry', 'Retry'), ('Sent', 'Sent'), ('Failed', 'Failed')], default='Sent', max_length=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='messages', to='main.clientmodel')),
                ('mailing_list', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='messages', to='main.mailmodel')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.AddField(
            model_name='mailmodel',
            name='tags',
            field=models.ManyToManyField(to='main.tagmodel'),
        ),
        migrations.AddField(
            model_name='clientmodel',
            name='code_mobile_operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='clients', to='main.codemobileoperatormodel'),
        ),
        migrations.AddField(
            model_name='clientmodel',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='clients', to='main.tagmodel'),
        ),
    ]
