# Generated by Django 4.2.1 on 2023-05-11 20:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_clientmodel_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagemodel',
            old_name='mailing_list',
            new_name='mail',
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='phone_number',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '7XXXXXXXXX'. Up to 11 digits allowed.", regex='^(7)\\d{10}$')]),
        ),
    ]
