# Generated by Django 4.2.1 on 2023-05-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_mailing_list_messagemodel_mail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailmodel',
            name='code_mobile_operators',
            field=models.ManyToManyField(blank=True, to='main.codemobileoperatormodel'),
        ),
        migrations.AlterField(
            model_name='mailmodel',
            name='tags',
            field=models.ManyToManyField(blank=True, to='main.tagmodel'),
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='send_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('Sent', 'Sent'), ('Failed', 'Failed')], default='Waiting', max_length=10),
        ),
    ]
